// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrcxlzcoooebognvgwxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyY3hsemNvb29lYm9nbnZnd3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjk3OTgsImV4cCI6MjA3Mzc0NTc5OH0.R3nvTVqUPoBKq3TIHSftyzb8qeemUJonxwrxxO0NxPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});